### PR TITLE
[Proposal] Create FUNDING.yml

### PR DESCRIPTION
**Pull request by Balinus**
This adds a funding link to Julia lang project.

See https://discourse.julialang.org/t/julialang-is-now-part-of-github-sponsors/34106

### CODE REVIEW

**Comment by visr** [comment]
Note that if you create a .github repo in the org and place it there, it will show this for all repos in the org, not just meta. Same thing was done in the linked post: https://github.com/JuliaLang/.github

**Comment by gaelforget** [comment]
A related announcement I got via tweet today is [https://github.com/sponsors/JuliaLang]()

Later in the week I might be able to read these posts & will try to learn more about the topic. Seems like a good idea a priori but important enough to take a bit of time to discuss & think about this...

**Comment by Balinus** [comment]
Indeed, this is here for discussion, not to quickly add this to the repo/org.

**Review by Datseris — APPROVED** [review]

**Comment by Alexander-Barth** [comment]
Thanks, @Balinus , of course I agree.

Can we earmark the "funds" to address the time-to-first-plot issue? just, kidding :-)

**Comment by Balinus** [comment]
@gaelforget Did you had any time to think about this? On my end, I don't see any important drawbacks.

**Comment by gaelforget** [comment]
> @gaelforget Did you had any time to think about this? On my end, I don't see any important drawbacks.

Hi @Balinus et al

Yes I think its a good idea with the understanding that we'd be essentially just highlighting an open source funding mechanism. 

The org wouldn't be directly involved with money transactions in any way, shape, form, or time -- correct?

This the main aspect I wanted to get confirmed + wait for others to have time to weigh in. I also thought it'd be good to test the thing first and convince myself that it's easy enough to opt out after one had opted in. I now feel confident in this regard. Everyone's institution, employer, or place of residency might have different rules and regulations. So this was a better-safe-than-sorry type of things for me cause I care that we remain as inclusive as possible. I hope that makes sense.

Thanks!!

**Comment by gaelforget** [comment]
I was looking for examples of how this would look like in `JuliaGeo`, `gher-ulg`, and `JuliaDynamics` but could not find badges. @visr, @Alexander-Barth, @Datseris could I please ask that you either 

- point me to the support Julia badges if they have indeed been added to your orgs
- let me know what (if anything) would have held you back regarding these badges

**Comment by gaelforget** [comment]
> Note that if you create a .github repo in the org and place it there, it will show this for all repos in the org, not just meta. Same thing was done in the linked post: https://github.com/JuliaLang/.github

The `.github` repo approach is probably be a hard no for me. In my opinion,

the decision of adding a badge like this (which potentially has legal implications) must rest with each  individual repo (or at least each individual team). 

Agreed?

(would be great if you all could please quote reply this & just add yes or say otherwise if you disagree with me -- as opposed to an emoji type response)

**Comment by Datseris** [comment]
I haven't used this in JuliaDynamics because I didn't know it existed. Besides, if someone wants to contribute to JuliaDynamics, I am welcoming/instructing them to use BountySource: https://juliadynamics.github.io/DynamicalSystems.jl/dev/#Contributing-and-Donating-1 . 
Keep in mind that this donation link really goes to JuliaLang and if at some point in the future JuliaClimate becomes big enough, we can consider such a link of our own. Until then, I whole-heartly agree with providing information on how to support Julia in general.

In my eyes this donation button does not mean payment. Instead, it represents a way for people to contribute to a cause they like when they do not have the time or skills to contribute code directly.

I totally understand how other people might have other priorities and or perception of open source, and different contracts. I agree with @gaelforget that it is probably not the most reasonable approach to make this as `.github` and thus be to every project by default. In fact, I would still say this even if @gaelforget hasn't expressed this amount of concern, because you can't really know what each repo will hold in the future...

I do have to make a comment though:

> the decision of adding a badge like this (which potentially has legal implications) 

This is something I really can't comprehend nor accept. We are simply providing information of how to aid the development of Julia-related code. How can this possibly have "any" implication for us? Sounds worse than dictatorship!

**Comment by visr** [comment]
>- point me to the support Julia badges if they have indeed been added to your orgs
> - let me know what (if anything) would have held you back regarding these badges

@gaelforget, JuliaGeo indeed does not have GitHub sponsors set up, but not for any reason other than nobody taking the initiative. I would personally be fine with a `.github` repo to set it by default for all, but only because it's less work and most repo's probably don't have an issue with it. Repos can always override the org FUNDING.yml ([example](https://github.com/rubocop-hq/rubocop/blob/master/.github/FUNDING.yml)). Perhaps making it empty or potentially [disabling it in the repo settings](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) could work to opt out.

> This file is overriding the organization-wide FUNDING.yml file. Removing FUNDING.yml in this repository will use the organization default. View organization funding file.

But if people feel strongly about not setting a default, I will not argue against it. Just pointing out [The Power of Defaults](https://blog.codinghorror.com/the-power-of-defaults/).

**Comment by Alexander-Barth** [comment]
https://github.com/gher-ulg/ is the github organization of our research group at the Universite of Liege which contains a quite diverse range of repos (julia, python, Fortran, ...). Having a sponsor link next to our repos would give the impression that I want to have funds for me or our research group which is not the case.

**Comment by Balinus** [comment]
I feel this should be a choice made at the repo-level. I'm closing this, feel free to re-open if you think otherwise.

**Pull request closed without merging**
